name: entroduction_graph_tool_env
channels:
  - defaults
  - conda-forge
  - ostrokach-forge
  - pkgw-forge
  - anaconda
  - psi4
  - numba
dependencies:
  - cgal=4.12
  - dbus=1.13.2
  - sparsehash=2.0.3
  - boost=1.66
  - pyopenssl=19.0.0
  - python=3.6
