name: entroduction_graph_tool_env
channels:
  - defaults
  - conda-forge
  - ostrokach-forge
  - pkgw-forge
  - Anaconda
dependencies:
  - python
  - pygobject
  - matplotlib
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - boost 
  - expat 
  - sparsehash 
  - gtk3 
  - cairo>=1.14
  - cairomm  
  - pycairo
  - graph-tool=2.27
