name: entroduction_graph_tool_env
channels:
  - defaults
  - conda-forge
  - ostrokach-forge
  - pkgw-forge
dependencies:
  - python
  - pygobject
  - matplotlib
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - cairo>=1.14
  - pycairo
  - graph-tool=2.27
