name: introduction_graph_tool_env
channels:
  - conda-forge
dependencies:
  - graph-tool=2.37
  - pandas
  - networkx=2.5
  - scikit-learn
  - tslearn
  - seaborn
  - matplotlib
  - scipy 
  - numpy
  - requests
  - ratelimiter
  - python-oauth2
  - pymongo
  - pycairo
  - oauthlib
  - nltk
  - googlemaps
  - future
  - statsmodels
  - beautifulsoup4
  - joblib
  - geocoder
  - backoff
  - git
  - pip:
    - powerlaw
    - python-louvain 
    - pandarallel
    - geopy
    - missingno
    - fuzzywuzzy
