name: entroduction_graph_tool_env
channels:
  - defaults
  - conda-forge
  - ostrokach-forge
  - pkgw-forge
  - anaconda
  - psi4
  - numba
dependencies:
  - cgal 
  - sparsehash 
  - boost=1.66
  - openssl=1.1.1
  - python=3.6
  - cairo
  - libsigcpp 
  - cairomm  
  - expat 
  - pycairo
  - numba 
  - py-boost 
  - matplotlib
  - scikit-learn
  - numpy
  - scipy
  - setuptools 
  - pandas
  - graphviz 
  - pygobject
  - gtk3
  - graph-tool=2.27
