name: entroduction_graph_tool_env
channels:
  - defaults
  - conda-forge
  - ostrokach-forge
  - pkgw-forge
  - anaconda
  - psi4
  - numba
dependencies:
  - cgal=4.12
  - dbus=1.13.2
  - sparsehash=2.0.3
  - boost=1.66
  - pyopenssl=19.0.0
  - python=3.6
  - cairo=1.14.12
  - libsigcpp=2.10.0
  - cairomm=1.12.2  
  - expat=2.2.6
  - pycairo=1.13.3
  - matplotlib=2.2.2
  - scikit-learn=0.22
  - numpy=1.17.4
  - scipy=1.3.2
  - setuptools=41.2.0
  - pandas=0.25.3
  - pygobject=3.28.2
  - gtk3=3.22
  - graph-tool=2.27
